# Generated by Django 3.2.7 on 2021-09-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
    ]
