# Generated by Django 3.2.7 on 2021-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self', '0002_auto_20210929_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('complain', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
